from Classes.Entity import Entity
from Classes.Grid import Grid
from Classes.Entities.import_entities import import_entities

needed = {"Flamethrower", "Axe", "Mushroom"}
items = import_entities(needed)

FLAMETHROWER = items["Flamethrower"]
AXE = items["Axe"]
MUSHROOM = items["Mushroom"]

# FOR THIS CLASS: Some code was generated by AI. Specifically, simple getters and setters were generated using the prompt
# Prompt: make me the getters and setters for the attributes of this class
# This was done very early in development, and was done mostly as a test of what AI is capable of in terms of working within the context of a project


class Player(Entity):
    """
    This Entity is the main controllable character of the game

    Attributes: 
        __item: The item the player is holding
        __mushroom_count: The number of mushrooms that a Player has collected
        __is_dead: Indicates if the Player is dead

        For other Attributes:
            See parent class
    """
    def __init__(self, pos: list, on_grid: Grid, ascii: str = "L", item: Entity | None = None):
        """ Initializes a Player with a given item

        Args: (only Args not passed to parent class are indicated)
            item: The item the player is holding 
        """
        super().__init__(pos, on_grid, ascii)
        self.__item = item
        self.__mushroom_count = 0
        self.__is_dead = False

    # * Simple Getters, AI generated with minor edits

    def get_item(self):
        """
        Returns: The item the player is holding
        """
        return self.__item

    def get_mushroom_count(self):
        """
        Returns: The number of mushrooms the player has collected 
        """
        return self.__mushroom_count

    def get_is_dead(self):
        """
        Returns: A bool indicating if the player is dead
        """
        return self.__is_dead

    # * Complex Getters

    def get_movement_validity(self, direction: str, r: int, c: int):
        """Overrides parent method. Allows player to move in previously invalid directions if holding certain items

        Args:
            See parent class
        
        Returns:
            See parent class
        """
        if not self.in_bounds(r, c):
            return False

        target_obj = self.get_obj_in_coord(r, c)

        if target_obj is None:
            return True

        if target_obj.get_burnable():
            if isinstance(self.get_item(), FLAMETHROWER):
                target_obj.burn_connected()
                self.set_item(None)
            if isinstance(self.get_item(), AXE):
                target_obj.chop()
                self.set_item(None)

        return super().get_movement_validity(direction, r, c)

    # * Simple Setters

    def kill(self):
        """
        Sets the player status to dead
        """
        self.__is_dead = True

    def set_item(self, item: Entity | None):
        """
        Sets an item to be held by the player

        Args: 
            item: The Entity for the player to hold
        """
        self.__item = item

    def increment_mushroom_count(self):
        """
        Increases mushroom count
        """
        self.__mushroom_count += 1
    
    def use_item(self):
        """
        Removes the current held item
        """
        self.__item = None

    # * Complex Setters

    def collect_item(self):
        """
        If on top of an item, collects it. Else, does nothing
        """
        item = self.get_entity_below()

        if not item:
            return

        if item.get_storable():
            self.set_item(item)
            item.destroy()

    def collect_shroom(self):
        """
        Collects the shroom below the player if it exists
        """
        shroom = self.get_entity_below()

        if not shroom:
            return

        if isinstance(shroom, MUSHROOM):
            self.increment_mushroom_count()
            shroom.destroy()

    def set_pos(self, direction: str):
        """
        Moves the player in desired direction, checks if movement kills them

        Args:
            direction: 'wasd', the desired direction of movement

        Returns: 
            True if the Player was able to move, False if not. Returns nothing if player dies
        """
        if super().set_pos(direction):
            entity_below = self.get_entity_below()
            if not entity_below:
                return True
            elif entity_below.get_deadly():
                self.kill()
                self.destroy()
            return True
        else:
            return False
