from Classes.Entity import Entity
from Classes.Grid import Grid
from Classes.Entities.import_entities import import_entities

# FOR THIS CLASS: Some code was generated by AI. Specifically, simple getters and setters were generated using the prompt
# Prompt: make me the getters and setters for the attributes of this class
# This was done very early in development, and was done mostly as a test of what AI is capable of in terms of working within the context of a project

# TODO Refactor this stuff
needed = {"Flamethrower", "Axe", "Mushroom", "Water"}
items = import_entities(needed)

Flamethrower = items["Flamethrower"]
Axe = items["Axe"]
Mushroom = items["Mushroom"]
Water = items["Water"]

class Player(Entity):

    def __init__(self, pos: list, on_grid: Grid, ascii = 'L',item: Entity | None = None):
        super().__init__(pos, on_grid, ascii)
        self.__item = item
        self.__mushroom_count = 0
        self.__is_dead = False

    def get_movement_validity(self, direction, r, c):
        on_grid = self.get_on_grid() # always get grid first
        # Is the target coordinate out of the Grid? then you cannot move. 
        if not (0<=r<len(on_grid.get_grid_obj_map()) and 0<=c<len(on_grid.get_grid_obj_map()[0])):
            return False
        
        target_obj = self.get_obj_in_coord(r, c)

        if target_obj == None: return True

        if target_obj.get_burnable():
            if isinstance(self.get_item(),Flamethrower):
                target_obj.burn_connected()
                self.set_item(None)  
            if isinstance(self.get_item(),Axe):
                target_obj.chop()
                self.set_item(None)
        if isinstance(target_obj, Water):
            self.kill()

        return super().get_movement_validity(direction, r, c)  

    # * Simple Getters, AI generated with minor edits

    def get_item(self): return self.__item

    def set_item(self, item: Entity | None): self.__item = item
    
    def use_item(self): self.__item = None

    def get_mushroom_count(self): return self.__mushroom_count

    def increment_mushroom_count(self): self.__mushroom_count += 1

    def get_is_dead(self): return self.__is_dead

    # * Complex Getters

    def get_above_item(self):
        item = super().get_above_entity()

        if not item: return False 

        return item if item.get_storable() else False

    def get_above_mushroom(self):
        shroom = super().get_above_entity()

        is_item = isinstance(shroom, Mushroom)

        if is_item: return shroom
        return False
    
    def get_above_water(self):
        puddle = super().get_above_entity()

        return isinstance(puddle, Water)
    
    # * Simple Setters

    def kill(self): self.__is_dead = True

    # * Complex Setters

    def collect_item(self):
        r,c = self.get_pos()
        on_grid = self.get_on_grid()

        item = self.get_above_item()

        if not self.get_above_item(): return

        if item.get_storable():
            self.set_item(item)
            item.destroy()

    #def collect_shroom(self):




