from Classes.Entities.import_entities import import_entities
from Classes.Entity import Entity
from Classes.Grid import Grid

needed = {"Flamethrower", "Axe", "Mushroom"}
items = import_entities(needed)

FLAMETHROWER = items["Flamethrower"]
AXE = items["Axe"]
MUSHROOM = items["Mushroom"]

# FOR THIS CLASS: Some code was generated by AI. Specifically, simple
# getters and setters were generated using the prompt.
# Prompt: make me the getters and setters for the attributes of this class
# This was done early in development as a small capability test.

# * RUFF CHECKED: No errors (12/10/2025)


class Player(Entity):
    """Represent the main controllable character of the game.

    Attributes:
        __item: The item the player is holding.
        __mushroom_count: The number of mushrooms the Player has collected.
        __is_dead: Indicates if the Player is dead.

    For other attributes, see the parent class.

    """

    def __init__(self, pos: list, on_grid: Grid, ascii_char: str = "L", item: Entity | None = None) -> None:
        """Initialize a Player with an optional held item.

        Args:
            pos: [r, c] position on the grid.
            on_grid: The grid containing the player.
            ascii_char: The ascii character for the Player.
            item: The optional item the player is holding.

        """
        super().__init__(pos, on_grid, ascii_char)
        self.__item = item
        self.__mushroom_count = 0
        self.__is_dead = False

    # * Simple Getters, AI generated with minor edits

    def get_item(self) -> Entity | None:
        """Return the item the player is holding.

        Returns:
            The held item or None if empty.

        """
        return self.__item

    def get_mushroom_count(self) -> int:
        """Return the number of mushrooms the player has collected.

        Returns:
            The mushroom count as an integer.

        """
        return self.__mushroom_count

    def get_is_dead(self) -> bool:
        """Return whether the player is dead.

        Returns:
            True if the player is dead, otherwise False.

        """
        return self.__is_dead

    # * Complex Getters

    def get_movement_validity(self, direction: str, r: int, c: int) -> bool:
        """Override parent's movement validity to allow item-based actions.

        Args:
            direction: Movement direction ('w','a','s','d').
            r: Target row.
            c: Target column.

        Returns:
            True if movement is allowed, otherwise False.

        """
        if not self.in_bounds(r, c):
            return False

        target_obj = self.get_obj_in_coord(r, c)

        if target_obj is None:
            return True

        if target_obj.get_burnable():
            if isinstance(self.get_item(), FLAMETHROWER):
                target_obj.burn_connected()
                self.set_item(None)
            if isinstance(self.get_item(), AXE):
                target_obj.chop()
                self.set_item(None)

        return super().get_movement_validity(direction, r, c)

    # * Simple Setters

    def kill(self) -> None:
        """Mark the player as dead."""
        self.__is_dead = True

    def set_item(self, item: Entity | None) -> None:
        """Set the item to be held by the player.

        Args:
            item: The Entity for the player to hold.

        """
        self.__item = item

    def increment_mushroom_count(self) -> None:
        """Increase the player's mushroom count by one."""
        self.__mushroom_count += 1

    def use_item(self) -> None:
        """Remove the currently held item."""
        self.__item = None

    # * Complex Setters

    def collect_item(self) -> None:
        """Collect the item below the player if it is storable."""
        item = self.get_entity_below()

        if not item:
            return

        if item.get_storable():
            self.set_item(item)
            item.destroy()

    def collect_shroom(self) -> None:
        """Collect the mushroom below the player if present."""
        shroom = self.get_entity_below()

        if not shroom:
            return

        if isinstance(shroom, MUSHROOM):
            self.increment_mushroom_count()
            shroom.destroy()

    def set_pos(self, direction: str) -> bool:
        """Move the player in the given direction and handle collisions.

        Args:
            direction: 'wasd', the desired direction of movement.

        Returns:
            True if the Player moved successfully, False otherwise.

        """
        if super().set_pos(direction):
            entity_below = self.get_entity_below()
            if not entity_below:
                return True
            if entity_below.get_deadly():
                self.kill()
                self.destroy()
            return True
        return False
