from Classes.Entity import Entity
from Classes.Grid import Grid
from Classes.Entities.import_entities import import_entities
import Utils.sounds as s

needed = {"Flamethrower", "Axe", "Mushroom", "PavedTile"}
items = import_entities(needed)

FLAMETHROWER = items["Flamethrower"]
AXE = items["Axe"]
MUSHROOM = items["Mushroom"]
PAVEDTILE = items['PavedTile']

# FOR THIS CLASS: Some code was generated by AI. Specifically, simple getters and setters were generated using the prompt
# Prompt: make me the getters and setters for the attributes of this class
# This was done very early in development, and was done mostly as a test of what AI is capable of in terms of working within the context of a project


class Player(Entity):

    def __init__(self, pos: list, on_grid: Grid, ascii: str = 'L',item: Entity | None = None):
        super().__init__(pos, on_grid, ascii)
        self.__item = item
        self.__mushroom_count = 0
        self.__is_dead = False

    # * Simple Getters, AI generated with minor edits

    def get_item(self): return self.__item

    def set_item(self, item: Entity | None): self.__item = item

    def get_mushroom_count(self): return self.__mushroom_count

    def increment_mushroom_count(self): self.__mushroom_count += 1

    def get_is_dead(self): return self.__is_dead

    # * Complex Getters

    def get_movement_validity(self, direction : str, r : int, c : int):
        if not self.in_bounds(r, c): return False
        
        target_obj = self.get_obj_in_coord(r, c)

        if target_obj == None: return True

        if target_obj.get_burnable():
            if isinstance(self.get_item(),FLAMETHROWER):
                target_obj.burn_connected()
                s.flamethrower_sound()
                self.set_item(None)  
            if isinstance(self.get_item(),AXE):
                target_obj.chop()
                self.set_item(None)
                
        return super().get_movement_validity(direction, r, c)  
    
    # * Simple Setters

    def kill(self): self.__is_dead = True

    # * Complex Setters

    def use_item(self):
        equipped = self.get_item()
        if not equipped: return

        elif equipped.get_passive(): equipped.use()

        self.set_item(None)

    def collect_item(self):
        item = self.get_entity_below()

        if not item: return

        if item.get_storable():
            self.set_item(item)
            item.destroy()

    def collect_shroom(self):
        shroom = self.get_entity_below()

        if not shroom: return

        if isinstance(shroom, MUSHROOM):
            s.shroom_sound()
            self.increment_mushroom_count()
            shroom.destroy()

    def set_pos(self, direction : str):
        if super().set_pos(direction):
            entity_below = self.get_entity_below()
            if entity_below:
                if entity_below.get_deadly():
                    self.kill()
                    self.destroy()
                elif isinstance(entity_below, PAVEDTILE):
                    s.paved_walk()
                else:
                    s.walk_sound()
            else:
                s.walk_sound()
            
            self.get_on_grid().set_player_pos(self.get_pos())

            return True
        else:
            return False

        




