import Utils.sounds as s
from Classes.Entities.import_entities import import_entities
from Classes.Entity import Entity
from Classes.Grid import Grid

needed = {"Flamethrower", "Axe", "Mushroom", "PavedTile", "Bomb", "Log", "Tree", "Bee", "Water"}
items = import_entities(needed)

FLAMETHROWER = items["Flamethrower"]
AXE = items["Axe"]
MUSHROOM = items["Mushroom"]
PAVEDTILE = items["PavedTile"]
BOMB = items["Bomb"]
LOG = items["Log"]
TREE = items["Tree"]
BEE = items["Bee"]
WATER = items["Water"]

# FOR THIS CLASS: Some code was generated by AI. Specifically, simple getters and setters were generated using the prompt
# Prompt: make me the getters and setters for the attributes of this class
# This was done very early in development, and was done mostly as a test of what AI is capable of in terms of working within the context of a project


class Player(Entity):
    """
    This Entity is the main controllable character of the game.

    Attributes: 
        __item: The item the player is holding
        __mushroom_count: The number of mushrooms that a Player has collected
        __is_dead: Indicates if the Player is dead
        Additionally, see parent class.

    """
    def __init__(self, pos: list, on_grid: Grid, ascii: str = "L", item: Entity | None = None):
        """ Initializes a Player with a given item

        Args:
            item: The item the player is holding 
            Additionally, see parent class.
        """   
        super().__init__(pos, on_grid, ascii)
        self.__item = item
        self.__mushroom_count = 0
        self.__is_dead = False

    # * Simple Getters, AI generated with minor edits

    def get_item(self):
        """
        Returns: The item the player is holding
        """
        return self.__item

    def get_mushroom_count(self):
        """
        Returns: The number of mushrooms the player has collected 
        """
        return self.__mushroom_count

    def get_is_dead(self):
        return self.__is_dead

    # * Complex Getters

    def get_movement_validity(self, direction: str, r: int, c: int):
        """Overrides parent method. Allows player to move in previously invalid directions if holding certain items

        Args:
            See parent class
        
        Returns:
            See parent class
        """
        if not self.in_bounds(r, c):
            return False

        target_obj = self.get_obj_in_coord(r, c)

        if target_obj is None:
            return True

        if target_obj.get_burnable():
            if isinstance(self.get_item(), FLAMETHROWER):
                target_obj.burn_connected()
                self.set_item(None)
            if isinstance(self.get_item(), AXE):
                target_obj.chop()
                s.axe_sound()
                self.set_item(None)

        return super().get_movement_validity(direction, r, c)

    # * Simple Setters
    def set_item(self, item: Entity | None):
        """
        Sets an item to be held by the player

        Args: 
            item: The Entity for the player to hold
        """
        # specific check for bomb:
        if isinstance(self.get_item(), BOMB) and isinstance(item, BOMB):
            self.get_item().increment_radius()
            return

        self.__item = item
    
    def increment_mushroom_count(self):
        """
        Increases mushroom count by one
        """
        self.__mushroom_count += 1

    def kill(self):
        """
        Sets the player status to dead
        """
        killer = self.get_entity_below()

        if isinstance(killer, BEE):
            s.bee_death_sound()
        elif isinstance(killer, WATER):
            s.water_sound()

        self.__is_dead = True

    # * Complex Setters

    def use_item(self):
        """
        Uses the current held item
        """
        equipped = self.get_item()
        if not equipped:
            return

        elif equipped.get_passive():
            equipped.use()
            self.set_item(None)

    def collect_item(self):
        """
        If on top of an item, collects it. Otherwise, does nothing
        """
        item = self.get_entity_below()

        if not item:
            return

        if item.get_storable():
            s.equip_sound()
            self.set_item(item)
            item.destroy()

    def collect_shroom(self):
        """
        Collects the shroom below the player if it exists
        """
        shroom = self.get_entity_below()

        if not shroom:
            return

        if isinstance(shroom, MUSHROOM):
            s.shroom_sound()
            self.increment_mushroom_count()
            shroom.destroy()

    def set_pos(self, direction: str):
        """
        Moves the player in desired direction, checks if movement kills them

        Activated any triggers if there are.

        Args:
            direction: 'wasd', the desired direction of movement

        Returns: 
            True if the Player was able to move, False if not. Returns nothing if player dies
        """
        if super().set_pos(direction):
            entity_below = self.get_entity_below()
            if entity_below:
                if entity_below.get_tile_trigger():
                    entity_below.trigger(self)

                if entity_below.get_deadly():
                    self.kill()
                    self.destroy()

                elif isinstance(entity_below, PAVEDTILE):
                    s.paved_walk()

                elif entity_below is not None:
                    s.on_item_sound()
            else:
                s.walk_sound()

            self.get_on_grid().set_player_pos(self.get_pos())

            return True
        else:
            return False
